language: go
go:
  - 1.x
services:
  - mysql
  - redis-server

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y
  - go get github.com/benbjohnson/ego/cmd/ego
script: make test-ci

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      make docker;
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push keratin/authn-server:latest;
    fi
